services:
  mongodb:
    image: 'mongodb/mongodb-community-server:latest'
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=UnJeDUoekbApK74MZ066X7rBLdRWDcZI'
  minio:
    image: 'minio/minio'
    hostname: 'minio'
    volumes:
      - 'minio_data:/data'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - 'MINIO_ROOT_USER=root'
      - 'MINIO_ROOT_PASSWORD=wIb8nv85LorMvMLgXrj1IjSonWhmoeIO'
    command: 'server /data --console-address ":9001"'
  
  minio_createbucket:
    image: 'minio/mc'
    depends_on:
      - 'minio'
    environment:
      - 'MC_HOST_minio=http://root:wIb8nv85LorMvMLgXrj1IjSonWhmoeIO@minio:9000'
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc mb minio/snappy;
      /usr/bin/mc admin user svcacct add --access-key ltX0fh99TwfdHYSVg1ff --secret-key Kh5FgbtOd04CIEklre79PVEwm5SSY9Hb7iroQobL minio/ root;
      exit 0;
      "
  
  api-server:
    build: './backend'
    depends_on:
      mongodb:
        condition: service_started
      minio:
        condition: service_started
    ports:
    - '8000:8000'


volumes:
  minio_data: